import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type React from "react";
// import { 
//   Roboto_Flex as Roboto, 
//   Bai_Jamjuree as BaiJamjuree 
// } from 'next/font/google'



// const roboto = Roboto({subsets: ['latin'], variable: '--font-roboto'})
// const baiJamjuree = BaiJamjuree({
//   subsets: ['latin'],
//    weight: '700',
//    variable: '--font-bai-jamjuree'
//   })


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
